[package]
name = "ruready"
version = "0.2.0-dev"
edition = "2024"

[dependencies]
config = { version = "0.15.13", default-features = false, features = ["toml"] }
directories = "6.0.0"
inquire = "0.7.5"
clipboard = "0.5.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
